services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "password123"
    platform: linux/amd64
    ports:
      - "1433:1433"

